---
title: "Corona Virus Report"
author:
- familyname: XXXX
  othernames: XXX
  address: Monash Universtidy
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
- familyname: XXXX
  othernames: Reports
  address: XXX
  qualifications: XXX
- familyname: XXX
  othernames: XXX
  address: XXX
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
department: Our consultancy \newline add names &\newline add names
organization: Australian Government COVID19
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries

library(tidyverse)
library(readr)

library(bookdown)

```



\section*{Country XX1 and YY1"}

\section*{Country XX2 and YY2}
```{r}
dat <- read.csv(file = "Data/worldwidecases.csv")
```

```{r tab2}
dat2 <- dat %>% 
  filter(countriesAndTerritories == c("China", "Russia")) %>% 
  pivot_wider(
    names_from = "countriesAndTerritories",
    values_from = "cases"  ) 
 knitr::kable(head(dat2[, 1:11]), caption = "China and Russia")


  

```
 
We can see the table\@ref(tab:tab2)).

```{r nicefig}
dat3 <- dat2 %>% 
  select("China", "Russia") 
  

```







\section*{Country XX3 and YY3}



